//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryIs2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PM05Account> PM05Account { get; set; }
        public virtual DbSet<PM05AccountType> PM05AccountType { get; set; }
        public virtual DbSet<PM05Author> PM05Author { get; set; }
        public virtual DbSet<PM05Book> PM05Book { get; set; }
        public virtual DbSet<PM05Extradition> PM05Extradition { get; set; }
        public virtual DbSet<PM05Publisher> PM05Publisher { get; set; }
        public virtual DbSet<PM05Reader> PM05Reader { get; set; }
        public virtual DbSet<PM05Section> PM05Section { get; set; }
    }
}
