//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryIs2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM05Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PM05Book()
        {
            this.PM05Extradition = new HashSet<PM05Extradition>();
            this.PM05Author = new HashSet<PM05Author>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdSection { get; set; }
        public int IdPublisher { get; set; }
        public int YearPub { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    
        public virtual PM05Publisher PM05Publisher { get; set; }
        public virtual PM05Section PM05Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PM05Extradition> PM05Extradition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PM05Author> PM05Author { get; set; }
    }
}
