//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryIs2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM05Extradition
    {
        public int Id { get; set; }
        public System.DateTime DateExtradition { get; set; }
        public System.DateTime DateRefund { get; set; }
        public bool Passed { get; set; }
        public int IdReader { get; set; }
        public int IdBook { get; set; }
        public int IdAccount { get; set; }
    
        public virtual PM05Account PM05Account { get; set; }
        public virtual PM05Book PM05Book { get; set; }
        public virtual PM05Reader PM05Reader { get; set; }
    }
}
